version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: equiroz
      MONGO_INITDB_ROOT_PASSWORD: equiroz
